### ISSUE TITLE
Making a game with these models?

### ISSUE THREAD

**Issue by guizx** [theripper93/canvas3dtokencompendium#65]
Hi, I wold like to make a game and sell it on steam using the models available here. I would use and modify them to include in the game.
But I was a little uncertain about the licensing regarding the colorized ones. 
I understand that the mz4250 models can be used in commercially as long as I pay the specific commercial tier on his patreon, but the colorized ones is uncertain to me.
Can you help me understand? Thanks.

**Comment by theripper93** [comment]
You cannot sell ether the colored or non colored ones
